version: '1'

services:
	postgres:
		image: postgres:9.6
		container_name: postgres
		environment:
			POSTGRES_USER: recommendation
			POSTGRES_PASSWORD: J5brHrAXFLQSif0K
			POSTGRES_DB: recommendation

	recommendation:
		build: .
		image: chamaconekt/recommendation
		links:
		- postgres
		container_name: recommendation
		depends_on:
			- postgres
		environment:

	nginx:
		image: nginx:1.11.11-alpine
		links:
			- recommendation
		container_name: nginx
		command: nginx -g 'daemon off;' -c /etc/recommendation-nginx/nginx.conf
		depends_on:
			- recommendation
		ports:
			- 80:80
		volumes_from:
			- recommendation

volumes:
	recommendation-static-files:
		driver:local